###
POST http://localhost:4001/api/cotizador/moneda/agregar HTTP/1.1

###
PUT http://localhost:4001/api/cotizador/moneda/edit/:id HTTP/1.1

###
DELETE http://localhost:4001/api/cotizador/moneda/delete/:id HTTP/1.1

###
GET http://localhost:4001/api/cotizador/sp/view HTTP/1.1